### ISSUE TITLE
Pre-populated new notebooks with header material in a cell

### ISSUE THREAD

**Issue by papajohn** [dsten/jupyterhub-deploy#1]
Ideally, every new notebook on `ds8.berkeley.edu` would start with the following content in the top cell.

```
# HIDDEN
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
```

**Comment by ryanlovett** [comment]
An ugly approximation is to put the boilerplate into a file for the students in and then have them load it with "%load header.py".

The exec_lines or exec_files methods to InteractiveShellApp get run at the start of a session and might be more elegant. I don't know if the js would properly hide the cell though. I'll try this out in another deployment like dsten.

**Comment by papajohn** [comment]
It's fine with me if this content just gets magically executed, rather than
appearing in a cell, in case that's easier.

**Comment by ryanlovett** [comment]
The easiest solution was to add your code as 10-header.ipy to /etc/skel/.ipython/profile_default/startup/ and to the corresponding directory of each existing user. Can you confirm that it behaves as expected?

Future direction for this: https://groups.google.com/forum/#!msg/jupyter/fBXTA5ef3Oo/29ox-4_kEAAJ

**Comment by papajohn** [comment]
Perfect! Can we update `datascience` before tomorrow?

**Comment by ryanlovett** [comment]
Yes. Though it shouldn't cause any disruption, I will rebuild the
singleuser container later this evening. Students will need to restart
active servers to see the changes.


Ryan

**Comment by ryanlovett** [comment]
I just rebuilt the notebook container with datascience==0.3.3.
